#if WITH_DEV_AUTOMATION_TESTS

#include "Misc/AutomationTest.h"
#include "Engine/World.h"
#include "InputAction.h"
#include "UObject/Script.h"
#include "Game/Common/WuwaGameTags.h"
#include "Game/Controller/WuwaPlayerController.h"
#include "Game/Input/DataAsset/WuwaInputDataAsset.h"
#include "Game/Input/WuwaInputRouterComponent.h"
#include "Game/NewWorld/Character/Role/WuwaCharacter.h"
#include "Game/NewWorld/Character/Role/Component/WuwaRoleGaitBridgeComponent.h"
#include "Game/NewWorld/Character/Common/Component/Abilities/WuwaUnifiedStateBridgeComponent.h"
#include "Game/NewWorld/Character/Common/Component/Anim/WuwaAnimDataLibrary.h"
#include "Game/NewWorld/Character/Common/Component/Anim/WuwaAnimLogicParams.h"
#include "Game/NewWorld/Character/Common/Component/Anim/WuwaLocomotionMath.h"
#include "Game/NewWorld/Character/Common/Component/Input/WuwaMoveInputHandler.h"
#include "Game/NewWorld/Character/Common/Component/Move/WuwaMovementComponent.h"

namespace WuwaUnifiedMovementStateTests
{
	// Exercise generated managed UClasses through their native reflection bridge. There is no mock
	// policy and no call to a native _Implementation fallback. No physics/animation tick is required.
	struct FFixture
	{
		UWorld* World = UWorld::CreateWorld(EWorldType::Game, false);
		AWuwaPlayerController* Controller = nullptr;
		AWuwaCharacter* Character = nullptr;
		UWuwaMovementComponent* Movement = nullptr;
		UWuwaRoleGaitBridgeComponent* Gait = nullptr;
		UWuwaUnifiedStateBridgeComponent* State = nullptr;
		FInputDataAsset MoveBinding;
		FInputDataAsset WalkRunBinding;
		FInputDataAsset SprintBinding;

		FFixture()
		{
			if (!World) return;
			FActorSpawnParameters Spawn;
			Spawn.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
			Spawn.ObjectFlags |= RF_Transient;
			Controller = World->SpawnActor<AWuwaPlayerController>(Spawn);
			Character = World->SpawnActor<AWuwaCharacter>(Spawn);
			if (!Controller || !Character) return;
			// Possess requires gameplay PlayerState initialization; this fixture only needs ownership.
			Controller->SetPawn(Character);
			Character->Controller = Controller;
			Controller->RegisterInputRouteHandlers();
			Controller->MoveInputHandler->OnMove.AddUniqueDynamic(Character, &AWuwaCharacter::HandleMoveInput);
			Movement = Character->GetWuwaMovementComponent();
			if (!Movement) return;
			Movement->MovementMode = MOVE_Walking;
			if (!Character->EnsureMovementStateSystem()) return;
			Gait = Character->RoleGaitComponent;
			State = Character->UnifiedStateComponent;
			Gait->RefreshPolicy();
			const FWuwaGameTags Tags = FWuwaGameTags::Get();
			MoveBinding = MakeBinding(Tags.Player_Common_Movement_Move, Tags.Input_Route_Movement, EInputActionValueType::Axis2D);
			WalkRunBinding = MakeBinding(Tags.Player_Common_Movement_WalkRun, Tags.Input_Route_Movement);
			SprintBinding = MakeBinding(Tags.Abilities_Movement_Dash, Tags.Input_Route_Ability);
		}

		~FFixture()
		{
			if (IsValid(Controller)) Controller->SetPawn(nullptr);
			if (World) World->DestroyWorld(false);
		}

		FInputDataAsset MakeBinding(FGameplayTag Tag, FGameplayTag Route,
			EInputActionValueType ValueType = EInputActionValueType::Boolean) const
		{
			FInputDataAsset Binding;
			UInputAction* Action = NewObject<UInputAction>(Controller);
			Action->ValueType = ValueType;
			Binding.InputAction = Action;
			Binding.InputTag = Tag;
			Binding.RouteTag = Route;
			return Binding;
		}

		bool IsReady(FAutomationTestBase& Test) const
		{
			if (!Test.TestNotNull(TEXT("Test character exists"), Character)
				|| !Test.TestNotNull(TEXT("Character has CMC"), Movement)
				|| !Test.TestNotNull(TEXT("Managed gait policy loaded"), Gait)
				|| !Test.TestNotNull(TEXT("Managed unified state loaded"), State)) return false;
			bool bReady = Test.TestEqual(TEXT("Gait uses the configured generated class"),
				Gait->GetClass(), Character->RoleGaitClass.LoadSynchronous());
			bReady &= Test.TestEqual(TEXT("State uses the configured generated class"),
				State->GetClass(), Character->UnifiedStateClass.LoadSynchronous());
			// Check the UClass metatype without coupling the game module to UnrealSharp internals.
			bReady &= Test.TestEqual(TEXT("Gait class is generated by UnrealSharp, not the empty native bridge"),
				Gait->GetClass()->GetClass()->GetFName(), FName(TEXT("CSClass")));
			bReady &= Test.TestEqual(TEXT("Unified class is generated by UnrealSharp"),
				State->GetClass()->GetClass()->GetFName(), FName(TEXT("CSClass")));
			bReady &= Test.TestTrue(TEXT("Managed legality override is callable through ProcessEvent"),
				State->IsMoveStateLegal(EWuwaPositionState::Ground, EWuwaMoveState::Walk));
			return bReady;
		}

		bool Dispatch(const FInputDataAsset& Binding, EWuwaInputPhase Phase, double Time,
			const FInputActionValue& Value = FInputActionValue(false)) const
		{
			World->TimeSeconds = Time;
			FWuwaInputEvent Event;
			// Match PlayerController's event construction: the router consumes a complete
			// event and does not look up an InputDataAsset binding on the caller's behalf.
			Event.InputTag = Binding.InputTag;
			Event.RouteTag = Binding.RouteTag;
			Event.SourceAction = Binding.InputAction;
			Event.Phase = Phase;
			Event.Timestamp = Time;
			Event.Value = Value;
			// The transient world deliberately skips BeginPlay. AActor::ProcessEvent otherwise
			// discards OnMove's dynamic callback even though the route handler reports success.
			// Permit reflection dispatch here without bypassing the real Router/delegate path.
			FEditorScriptExecutionGuard ScriptExecutionGuard;
			return Controller->GetInputRouter()->DispatchInput(Event);
		}

		bool Move(FVector2D Axis, double Time) const
		{
			const bool bHandled = Dispatch(MoveBinding, Axis.IsNearlyZero() ? EWuwaInputPhase::Released : EWuwaInputPhase::Triggered,
				Time, FInputActionValue(Axis));
			Movement->ConsumeInputVector();
			return bHandled;
		}

		void Sample(UObject* Window, double Time) const
		{
			World->TimeSeconds = Time;
			const FWuwaPlayerInputState Input = Character->GetPlayerInputState();
			Movement->UpdateSprintDesireWindow(Window, Input.bSprintHeld ? Input.SprintHeldSeconds : 0.f, 0.2f);
		}

		FWuwaLocomotionAnimData Snapshot(FAutomationTestBase& Test) const
		{
			UWuwaAnimLogicParams* Params = NewObject<UWuwaAnimLogicParams>(Character);
			Test.TestTrue(TEXT("Animation captures the actual state components"),
				UWuwaAnimDataLibrary::UpdateAnimationData(Movement, Params));
			return WuwaLocomotion::BuildAnimationData(Params->GetMoveData(), Params->GetStateData(), true, 5.f, 2.f, 0.01f);
		}
	};
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaManagedStateOwnershipTest, "Wuwa.Movement.ManagedState.LegalityAndOwnership",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaManagedStateOwnershipTest::RunTest(const FString& Parameters)
{
	using namespace WuwaUnifiedMovementStateTests;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	using P = EWuwaPositionState;
	using M = EWuwaMoveState;
	const TMap<P, TArray<M>> Legal = {
		{P::None, {M::Other}},
		{P::Ground, {M::Other, M::Stand, M::Walk, M::WalkStop, M::Run, M::RunStop, M::Sprint, M::SprintStop, M::Dodge}},
		{P::Air, {M::Other, M::Dodge, M::Jump, M::Fall, M::Glide, M::Flying}},
		{P::Climb, {M::Other, M::NormalClimb, M::FastClimb}},
		{P::Water, {M::Other, M::NormalSwim, M::FastSwim}}
	};
	for (const auto& Position : Legal)
	{
		for (uint8 Index = 0; Index <= static_cast<uint8>(M::Flying); ++Index)
		{
			const M Move = static_cast<M>(Index);
			TestEqual(FString::Printf(TEXT("Position %d / move %d legality"), static_cast<int32>(Position.Key), Index),
				F.State->IsMoveStateLegal(Position.Key, Move), Position.Value.Contains(Move));
		}
	}
	TestFalse(TEXT("Unknown position fails closed"), F.State->IsMoveStateLegal(static_cast<P>(255), M::Other));
	TestFalse(TEXT("Unknown movement fails closed"), F.State->IsMoveStateLegal(P::Ground, static_cast<M>(255)));
	TestFalse(TEXT("Ground state rejects airborne movement"), F.State->TrySetMoveState(M::Jump, EWuwaGait::Run));
	TestFalse(TEXT("Unknown gait fails closed"), F.State->TrySetMoveState(M::Stand, static_cast<EWuwaGait>(255)));
	const int32 InitialRevision = F.State->GetStateData().Revision;
	TestTrue(TEXT("The same valid state is an accepted no-op"), F.State->TrySetMoveState(M::Stand, EWuwaGait::Run));
	TestEqual(TEXT("Identical state does not publish another revision"), F.State->GetStateData().Revision, InitialRevision);

	TestTrue(TEXT("Semantic movement is routed"), F.Move(FVector2D(0.f, 1.f), 1.0));
	TestEqual(TEXT("The routed axis reaches the character through its dynamic delegate"),
		F.Character->GetPlayerInputState().MoveAxis, FVector2D(0.f, 1.f));
	TestTrue(TEXT("The managed context sees the routed movement intent"), F.Gait->ReadMovementContext().bHasMoveInput);
	UObject* OldAction = NewObject<UInputAction>(F.Character);
	UObject* NewAction = NewObject<UInputAction>(F.Character);
	const int32 OldHandle = F.State->AcquireMoveState(OldAction, M::Dodge, 100);
	TestTrue(TEXT("Dash acquires an action handle"), OldHandle > 0);
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Continuous movement does not overwrite the active action"), F.State->GetStateData().MoveState == M::Dodge);
	TestFalse(TEXT("Ordinary state requests cannot overwrite an action lease"), F.State->TrySetMoveState(M::Run, EWuwaGait::Run));
	TestEqual(TEXT("Lower priority action is rejected"), F.State->AcquireMoveState(NewAction, M::Dodge, 99), 0);
	const int32 NewHandle = F.State->AcquireMoveState(NewAction, M::Dodge, 100);
	TestTrue(TEXT("Equal priority replacement receives a distinct handle"), NewHandle > OldHandle);
	const int32 ReplacementRevision = F.State->GetStateData().Revision;
	TestFalse(TEXT("A late end from the old action cannot release the replacement"), F.State->ReleaseMoveState(OldHandle));
	TestEqual(TEXT("An invalid release does not publish"), F.State->GetStateData().Revision, ReplacementRevision);
	TestTrue(TEXT("The new action still owns the state"), F.State->GetStateData().bHasActionOverride);
	TestTrue(TEXT("The active owner can release"), F.State->ReleaseMoveState(NewHandle));
	TestFalse(TEXT("Releasing does not resurrect the old action"), F.State->GetStateData().bHasActionOverride);
	TestTrue(TEXT("Release recomputes Run from the held movement input"), F.State->GetStateData().MoveState == M::Run);

	F.Movement->Velocity = FVector(-310.f, 0.f, 0.f);
	const int32 NoInputDash = F.State->AcquireMoveState(NewAction, M::Dodge, 100);
	F.Move(FVector2D::ZeroVector, 1.2);
	const FWuwaLocomotionAnimData DuringDash = F.Snapshot(*this);
	TestTrue(TEXT("Animation exposes the managed action override"), DuringDash.bHasUnifiedState && DuringDash.bHasActionOverride);
	TestFalse(TEXT("Dash residual speed cannot trigger ordinary Stop animation"), DuringDash.bWantsToStop);
	TestFalse(TEXT("Dash is not ground locomotion"), DuringDash.bGroundMoveActive);
	TestTrue(TEXT("No-input Dash releases"), F.State->ReleaseMoveState(NoInputDash));
	TestTrue(TEXT("Residual Dash velocity does not manufacture RunStop"), F.State->GetStateData().MoveState == M::Stand);
	TestEqual(TEXT("State release never zeroes physical velocity"), F.Movement->Velocity, FVector(-310.f, 0.f, 0.f));
	TestFalse(TEXT("Animation remains out of Stop after no-input action release"), F.Snapshot(*this).bWantsToStop);

	UObject* DeadOwner = NewObject<UInputAction>(F.Character);
	const int32 DeadHandle = F.State->AcquireMoveState(DeadOwner, M::Dodge, 100);
	DeadOwner->MarkAsGarbage();
	F.State->PruneStateOwners();
	TestFalse(TEXT("A destroyed action owner cannot keep its lease"), F.State->GetStateData().bHasActionOverride);
	TestFalse(TEXT("A pruned handle never becomes active again"), F.State->ReleaseMoveState(DeadHandle));
	const int32 BeforeReset = F.State->AcquireMoveState(NewAction, M::Dodge, 100);
	F.State->ResetActionStates();
	const int32 AfterReset = F.State->AcquireMoveState(NewAction, M::Dodge, 100);
	TestTrue(TEXT("Reset does not reuse an old action handle"), AfterReset > BeforeReset);
	TestFalse(TEXT("A pre-reset End cannot release a post-reset action"), F.State->ReleaseMoveState(BeforeReset));
	F.State->ReleaseMoveState(AfterReset);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaManagedSprintPipelineTest, "Wuwa.Movement.ManagedState.RoutedSprintAndAnimation",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaManagedSprintPipelineTest::RunTest(const FString& Parameters)
{
	using namespace WuwaUnifiedMovementStateTests;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	using M = EWuwaMoveState;
	UWuwaMovementSettings* Settings = NewObject<UWuwaMovementSettings>(F.Character);
	Settings->Walk.MaxSpeed = 210.f;
	Settings->Walk.MaxAcceleration = 1200.f;
	Settings->Walk.GroundFriction = 6.f;
	Settings->Walk.BrakingDeceleration = 900.f;
	Settings->Sprint.MaxSpeed = 940.f;
	Settings->Sprint.MaxAcceleration = 2700.f;
	Settings->Sprint.GroundFriction = 4.f;
	Settings->Sprint.BrakingDeceleration = 1300.f;
	F.Movement->MovementSettings = Settings;
	TestTrue(TEXT("Movement command reaches the controlled character"), F.Move(FVector2D(0.f, 1.f), 1.0));
	TestTrue(TEXT("The movement command updates the character input snapshot"), F.Character->GetPlayerInputState().bHasMoveInput);
	TestTrue(TEXT("Walk/Run command reaches managed gait policy"), F.Dispatch(F.WalkRunBinding, EWuwaInputPhase::Pressed, 1.01));
	TestTrue(TEXT("Managed state accepts the Walk preference"), F.State->GetStateData().MoveState == M::Walk);
	F.Movement->Velocity = FVector(350.f, 0.f, 0.f);
	TestEqual(TEXT("Walk applies configured speed cap"), F.Movement->MaxWalkSpeed, 210.f);
	TestEqual(TEXT("Walk applies configured acceleration"), F.Movement->MaxAcceleration, 1200.f);
	TestEqual(TEXT("Walk applies configured friction"), F.Movement->GroundFriction, 6.f);
	TestEqual(TEXT("Walk applies configured braking"), F.Movement->BrakingDecelerationWalking, 900.f);

	UObject* Window = NewObject<UInputAction>(F.Character);
	F.World->TimeSeconds = 2.0;
	F.Movement->BeginSprintDesireWindow(Window);
	F.Movement->EndSprintDesireWindow(Window);
	TestTrue(TEXT("Temporary sprint is accepted through the managed state"), F.State->GetStateData().MoveState == M::Sprint);
	TestTrue(TEXT("Sprint keeps the saved Walk preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	TestEqual(TEXT("Sprint applies its own configured speed cap"), F.Movement->MaxWalkSpeed, 940.f);
	TestEqual(TEXT("Sprint applies its own configured acceleration"), F.Movement->MaxAcceleration, 2700.f);
	TestEqual(TEXT("Sprint applies its own configured friction"), F.Movement->GroundFriction, 4.f);
	TestEqual(TEXT("Sprint applies its own configured braking"), F.Movement->BrakingDecelerationWalking, 1300.f);
	F.State->ChangeDirectionState(EWuwaDirectionState::LockDirection);
	const FWuwaLocomotionAnimData Sprint = F.Snapshot(*this);
	TestTrue(TEXT("Anim snapshot reads actual unified Sprint"), Sprint.bHasUnifiedState && Sprint.MoveState == M::Sprint);
	TestTrue(TEXT("Anim snapshot carries Ground and direction state"), Sprint.PositionState == EWuwaPositionState::Ground
		&& Sprint.DirectionState == EWuwaDirectionState::LockDirection);
	TestTrue(TEXT("Accepted Sprint enables ground movement animation"), Sprint.bGroundMoveActive && Sprint.bStateGroundSprint);
	TestTrue(TEXT("Anim view keeps Walk preference and Sprint result separate"), Sprint.DesiredGait == EWuwaGait::Walk
		&& Sprint.AllowedGait == EWuwaGait::Sprint && Sprint.StopGait == EWuwaGait::Sprint);
	TestEqual(TEXT("Changing policy leaves actual speed independent of the cap"), Sprint.GroundSpeed, 350.f);
	F.World->TimeSeconds = 2.99;
	F.Gait->RefreshPolicy();
	F.Movement->EndSprintDesireWindow(Window);
	TestTrue(TEXT("Temporary sprint survives until its one-second deadline"), F.State->GetStateData().MoveState == M::Sprint);
	F.World->TimeSeconds = 3.0;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Expiration runs without an animation update or notify Tick"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Expiration restores the retained Walk preference"), F.State->GetStateData().MoveState == M::Walk);
	TestEqual(TEXT("Walk configuration is reapplied at expiry"), F.Movement->MaxWalkSpeed, 210.f);
	TestEqual(TEXT("Expiry does not reset velocity"), F.Movement->Velocity, FVector(350.f, 0.f, 0.f));

	// The same semantic Dash action drives the hold snapshot even when no ASC accepts a GA.
	TestNull(TEXT("This input path does not require a working ASC"), F.Controller->GetASC());
	F.Dispatch(F.SprintBinding, EWuwaInputPhase::Pressed, 4.0);
	F.Movement->BeginSprintDesireWindow(Window);
	F.Sample(Window, 4.2);
	TestTrue(TEXT("Exactly the threshold remains temporary"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::Temporary);
	F.Sample(Window, 4.21);
	TestTrue(TEXT("Routed semantic hold becomes sustained"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::Sustained);
	F.Movement->EndSprintDesireWindow(Window);
	F.Dispatch(F.SprintBinding, EWuwaInputPhase::Released, 4.3);
	F.Sample(Window, 4.4);
	TestTrue(TEXT("Release after window End cannot demote committed sustained sprint"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::Sustained);
	F.Move(FVector2D::ZeroVector, 4.5);
	TestTrue(TEXT("Releasing movement clears sustained request despite residual velocity"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Actual Sprint transitions to SprintStop"), F.State->GetStateData().MoveState == M::SprintStop);
	const FWuwaLocomotionAnimData Stop = F.Snapshot(*this);
	TestTrue(TEXT("Animation selects the last actual Sprint stop"), Stop.bWantsToStop && Stop.StopGait == EWuwaGait::Sprint);
	TestFalse(TEXT("Stop is not active ground locomotion"), Stop.bGroundMoveActive);
	F.Movement->Velocity = FVector::ZeroVector;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Completed stop settles to Stand"), F.State->GetStateData().MoveState == M::Stand);
	TestTrue(TEXT("Zero speed does not change the stop clip's saved gait"), F.Snapshot(*this).StopGait == EWuwaGait::Sprint);
	F.Move(FVector2D(0.f, 1.f), 5.0);
	TestTrue(TEXT("The next movement uses Walk rather than reviving Sprint"), F.State->GetStateData().MoveState == M::Walk);
	TestTrue(TEXT("The next actual gait updates StopGait"), F.Movement->GetStopGait() == EWuwaGait::Walk);
	F.Sample(Window, 5.3);
	F.Movement->EndSprintDesireWindow(Window);
	TestTrue(TEXT("Late window callbacks cannot revive a consumed request"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::None);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaManagedGaitRestrictionTest, "Wuwa.Movement.ManagedState.RestrictionsAndPosition",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaManagedGaitRestrictionTest::RunTest(const FString& Parameters)
{
	using namespace WuwaUnifiedMovementStateTests;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	using M = EWuwaMoveState;
	using P = EWuwaPositionState;
	TestTrue(TEXT("Restriction fixture receives the routed movement command"), F.Move(FVector2D(0.f, 1.f), 1.0));
	TestTrue(TEXT("Restriction policy starts with real movement input"), F.Gait->ReadMovementContext().bHasMoveInput);
	F.Gait->RequestDesiredGait(EWuwaGait::Walk);
	UObject* ReasonA = NewObject<UInputAction>(F.Character);
	UObject* ReasonB = NewObject<UInputAction>(F.Character);
	UObject* Window = NewObject<UInputAction>(F.Character);
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, true);
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, true);
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Sprint, true);
	F.Gait->RequestDesiredGait(EWuwaGait::Sprint);
	TestTrue(TEXT("A legacy Sprint request preserves Walk preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	TestTrue(TEXT("Blocked Sprint falls back to the preferred Walk"), F.State->GetStateData().MoveState == M::Walk);
	TestTrue(TEXT("Blocking execution does not erase the sprint request"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::Sustained);
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, false);
	F.Movement->SetSprintAllowed(true);
	TestFalse(TEXT("Removing one source, or the CMC compatibility source, cannot release another source"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Sprint, false);
	TestTrue(TEXT("Each blocking source releases only its own contribution"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	TestTrue(TEXT("Once every source releases, the pending request can resolve to Sprint"), F.State->GetStateData().MoveState == M::Sprint);
	F.Movement->ClearSprintDesire();
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Walk, true);
	TestTrue(TEXT("A blocked preference falls back to allowed Run"), F.State->GetStateData().MoveState == M::Run);
	TestTrue(TEXT("Fallback does not overwrite preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Run, true);
	TestTrue(TEXT("Disallowing both ground gaits resolves to Other"), F.State->GetStateData().MoveState == M::Other);
	const FWuwaLocomotionAnimData Blocked = F.Snapshot(*this);
	TestFalse(TEXT("Movement input cannot bypass restrictions in animation"), Blocked.bGroundMoveActive || Blocked.bIsGoingToMove);
	F.Gait->ResetSprintRequest();
	TestFalse(TEXT("Clearing sprint leaves other gait restrictions intact"), F.Gait->IsGaitAllowed(EWuwaGait::Walk));
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Walk, false);
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Run, false);
	UObject* DeadReason = NewObject<UInputAction>(F.Character);
	F.Gait->SetGaitBlocked(DeadReason, EWuwaGait::Sprint, true);
	DeadReason->MarkAsGarbage();
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("A destroyed restriction source cannot leave the gait permanently blocked"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));

	F.Movement->BeginSprintDesireWindow(Window);
	F.Movement->EndSprintDesireWindow(Window);
	F.Movement->BeginSprintDesireWindow(Window);
	const int32 Dash = F.State->AcquireMoveState(ReasonA, M::Dodge, 100);
	F.Movement->Velocity = FVector(170.f, 0.f, 210.f);
	F.Movement->MovementMode = MOVE_Falling;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Ground to Air follows the physical movement mode"), F.State->GetStateData().PositionState == P::Air);
	TestTrue(TEXT("An action legal in Air retains its handle across the position change"), F.State->GetStateData().bHasActionOverride);
	TestTrue(TEXT("Leaving Ground clears active and retained sprint requests"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("The retained airborne action can still release"), F.State->ReleaseMoveState(Dash));
	TestTrue(TEXT("Positive vertical velocity resolves to Jump"), F.State->GetStateData().MoveState == M::Jump);
	F.Movement->Velocity.Z = -10.f;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Negative vertical velocity resolves to Fall"), F.State->GetStateData().MoveState == M::Fall);
	F.Movement->MovementMode = MOVE_Flying;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Physical flying resolves to Flying"), F.State->GetStateData().MoveState == M::Flying);
	const int32 AirDash = F.State->AcquireMoveState(ReasonA, M::Dodge, 100);
	F.Movement->MovementMode = MOVE_Swimming;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Swimming resolves to Water / NormalSwim"), F.State->GetStateData().PositionState == P::Water
		&& F.State->GetStateData().MoveState == M::NormalSwim);
	TestFalse(TEXT("An action illegal in the new position loses its lease"), F.State->GetStateData().bHasActionOverride);
	TestFalse(TEXT("The invalidated airborne handle cannot revive"), F.State->ReleaseMoveState(AirDash));
	F.Movement->MovementMode = MOVE_Custom;
	F.Movement->CustomMovementMode = ECustomMoveMode::MOVE_Climb;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Climbing resolves to Climb / NormalClimb"), F.State->GetStateData().PositionState == P::Climb
		&& F.State->GetStateData().MoveState == M::NormalClimb);
	F.Movement->MovementMode = MOVE_None;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("No physical movement mode resolves to None / Other"), F.State->GetStateData().PositionState == P::None
		&& F.State->GetStateData().MoveState == M::Other);
	F.Movement->MovementMode = MOVE_Walking;
	F.Gait->RefreshPolicy();
	F.Movement->UpdateSprintDesireWindow(Window, 5.f, 0.2f);
	F.Movement->EndSprintDesireWindow(Window);
	TestTrue(TEXT("Returning to Ground retains Walk but not the departed sprint window"), F.State->GetStateData().MoveState == M::Walk
		&& F.Movement->GetSprintDesire() == EWuwaSprintDesire::None);
	TestEqual(TEXT("Policy changes never reset horizontal speed"), F.Movement->Velocity.X, 170.0);

	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, true);
	F.Movement->BeginSprintDesireWindow(Window);
	F.Movement->EndSprintDesireWindow(Window);
	F.Movement->BeginSprintDesireWindow(Window);
	const int32 ResetHandle = F.State->AcquireMoveState(ReasonA, M::Dodge, 100);
	F.Gait->ResetSprintRequest();
	TestTrue(TEXT("Sprint-only reset preserves action ownership"), F.State->GetStateData().bHasActionOverride);
	TestFalse(TEXT("Sprint-only reset preserves the restriction sources"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	F.Movement->BeginSprintDesireWindow(Window);
	F.Gait->ResetRuntime();
	TestFalse(TEXT("Runtime reset releases active actions"), F.State->GetStateData().bHasActionOverride);
	TestFalse(TEXT("A reset action's delayed End cannot affect new state"), F.State->ReleaseMoveState(ResetHandle));
	TestTrue(TEXT("Runtime reset clears all restriction sources"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	F.Movement->UpdateSprintDesireWindow(Window, 5.f, 0.2f);
	F.Movement->EndSprintDesireWindow(Window);
	TestTrue(TEXT("Runtime reset clears unfinished and retained sprint without late resurrection"), F.Movement->GetSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Runtime reset retains the player's Walk preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	return true;
}

#endif
