#if WITH_DEV_AUTOMATION_TESTS

#include "Misc/AutomationTest.h"
#include "Tests/Input/WuwaTestMoveInput.h"
#include "Tests/Movement/WuwaTestGait.h"
#include "Engine/World.h"
#include "InputAction.h"
#include "UObject/Script.h"
#include "Game/Common/WuwaGameTags.h"
#include "Game/Controller/WuwaPlayerController.h"
#include "Game/Input/DataAsset/WuwaInputDataAsset.h"
#include "Game/Input/WuwaInputRouterComponent.h"
#include "Game/NewWorld/Character/Role/WuwaCharacter.h"
#include "Game/NewWorld/Character/Role/Component/WuwaRoleGaitBridgeComponent.h"
#include "Game/NewWorld/Character/Common/Component/Abilities/WuwaUnifiedStateBridgeComponent.h"
#include "Game/NewWorld/Character/Common/Component/Anim/WuwaAnimDataLibrary.h"
#include "Game/NewWorld/Character/Common/Component/Anim/WuwaAnimLogicParams.h"
#include "Game/NewWorld/Character/Common/Component/Anim/WuwaLocomotionMath.h"
#include "Game/NewWorld/Character/Common/Component/Input/WuwaInputIntentComponent.h"
#include "Game/NewWorld/Character/Common/Component/Move/WuwaMovementComponent.h"
#include "WuwaStateEventRecorder.h"

namespace WuwaUnifiedMovementStateTests
{
	// Exercise generated managed UClasses through their native reflection bridge. There is no mock
	// policy and no call to a native _Implementation fallback. No physics/animation tick is required.
	struct FFixture
	{
		UWorld* World = UWorld::CreateWorld(EWorldType::Game, false);
		AWuwaPlayerController* Controller = nullptr;
		AWuwaCharacter* Character = nullptr;
		UWuwaMovementComponent* Movement = nullptr;
		UWuwaRoleGaitBridgeComponent* Gait = nullptr;
		UWuwaUnifiedStateBridgeComponent* State = nullptr;
		FInputDataAsset MoveBinding;
		FInputDataAsset WalkRunBinding;
		FInputDataAsset SprintBinding;

		FFixture()
		{
			if (!World) return;
			FActorSpawnParameters Spawn;
			Spawn.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
			Spawn.ObjectFlags |= RF_Transient;
			Controller = World->SpawnActor<AWuwaPlayerController>(Spawn);
			Character = World->SpawnActor<AWuwaCharacter>(Spawn);
			if (!Controller || !Character) return;
			// Possess requires gameplay PlayerState initialization; this fixture only needs ownership.
			Controller->SetPawn(Character);
			Character->Controller = Controller;
			Controller->RegisterInputRouteHandlers();
			WuwaTestInput::UseTestMoveInputConfig(Controller);
			Movement = Character->GetWuwaMovementComponent();
			if (!Movement) return;
			Movement->MovementMode = MOVE_Walking;
			if (!Character->EnsureMovementStateSystem()) return;
			Gait = Character->RoleGaitComponent;
			State = Character->UnifiedStateComponent;
			Gait->RefreshPolicy();
			const FWuwaGameTags Tags = FWuwaGameTags::Get();
			MoveBinding = MakeBinding(Tags.Player_Common_Movement_Move, Tags.Input_Route_Movement, EInputActionValueType::Axis2D);
			WalkRunBinding = MakeBinding(Tags.Player_Common_Movement_WalkRun, Tags.Input_Route_Movement);
			SprintBinding = MakeBinding(Tags.Abilities_Movement_Dash, Tags.Input_Route_Ability);
		}

		~FFixture()
		{
			if (IsValid(Controller)) Controller->SetPawn(nullptr);
			if (World) World->DestroyWorld(false);
		}

		FInputDataAsset MakeBinding(FGameplayTag Tag, FGameplayTag Route,
			EInputActionValueType ValueType = EInputActionValueType::Boolean) const
		{
			FInputDataAsset Binding;
			UInputAction* Action = NewObject<UInputAction>(Controller);
			Action->ValueType = ValueType;
			Binding.InputAction = Action;
			Binding.InputTag = Tag;
			Binding.RouteTag = Route;
			return Binding;
		}

		bool IsReady(FAutomationTestBase& Test) const
		{
			if (!Test.TestNotNull(TEXT("Test character exists"), Character)
				|| !Test.TestNotNull(TEXT("Character has CMC"), Movement)
				|| !Test.TestNotNull(TEXT("Managed gait policy loaded"), Gait)
				|| !Test.TestNotNull(TEXT("Managed unified state loaded"), State)) return false;
			bool bReady = Test.TestEqual(TEXT("Gait uses the configured generated class"),
				Gait->GetClass(), Character->RoleGaitClass.LoadSynchronous());
			bReady &= Test.TestEqual(TEXT("State uses the configured generated class"),
				State->GetClass(), Character->UnifiedStateClass.LoadSynchronous());
			// Check the UClass metatype without coupling the game module to UnrealSharp internals.
			bReady &= Test.TestEqual(TEXT("Gait class is generated by UnrealSharp, not the empty native bridge"),
				Gait->GetClass()->GetClass()->GetFName(), FName(TEXT("CSClass")));
			bReady &= Test.TestEqual(TEXT("Unified class is generated by UnrealSharp"),
				State->GetClass()->GetClass()->GetFName(), FName(TEXT("CSClass")));
			bReady &= Test.TestTrue(TEXT("Managed legality override is callable through ProcessEvent"),
				State->IsMoveStateLegal(EWuwaPositionState::Ground, EWuwaMoveState::Walk));
			return bReady;
		}

		bool Dispatch(const FInputDataAsset& Binding, EWuwaInputPhase Phase, double Time,
			const FInputActionValue& Value = FInputActionValue(false)) const
		{
			World->TimeSeconds = Time;
			FWuwaInputEvent Event;
			// Match PlayerController's event construction: the router consumes a complete
			// event and does not look up an InputDataAsset binding on the caller's behalf.
			Event.InputTag = Binding.InputTag;
			Event.RouteTag = Binding.RouteTag;
			Event.SourceAction = Binding.InputAction;
			Event.Phase = Phase;
			Event.Timestamp = Time;
			Event.Value = Value;
			// The transient world deliberately skips BeginPlay. AActor::ProcessEvent otherwise
			// discards reflected handler calls even though the route handler reports success.
			// Permit reflection dispatch here without bypassing the real Router/delegate path.
			FEditorScriptExecutionGuard ScriptExecutionGuard;
			return Controller->RouteInputEvent(Event);
		}

		// 移动轴记录进角色的输入意图，不经过 Router 的 Handler；返回角色是否收到了这次输入。
		bool Move(FVector2D Axis, double Time) const
		{
			Dispatch(MoveBinding, Axis.IsNearlyZero() ? EWuwaInputPhase::Released : EWuwaInputPhase::Triggered,
				Time, FInputActionValue(Axis));
			// 测试不跑世界 Tick：手动执行本帧 CMC 物理更新前的 RoleGait 刷新。
			Gait->RefreshPolicy();
			return Character->InputIntent->GetMoveIntent().Axis.Equals(Axis);
		}

		void Sample(UObject* Window, double Time) const
		{
			World->TimeSeconds = Time;
			const FWuwaPlayerInputState Input = Character->GetPlayerInputState();
			WuwaTestGait::Of(Movement)->SampleSprintWindow(Window, Input.bSprintHeld ? Input.SprintHeldSeconds : 0.f, 0.2f);
		}

		FWuwaLocomotionAnimData Snapshot(FAutomationTestBase& Test) const
		{
			UWuwaAnimLogicParams* Params = NewObject<UWuwaAnimLogicParams>(Character);
			Test.TestTrue(TEXT("Animation captures the actual state components"),
				UWuwaAnimDataLibrary::UpdateAnimationData(Movement, Params));
			return WuwaLocomotion::BuildAnimationData(Params->GetMoveData(), Params->GetStateData(), true, 5.f, 2.f, 0.01f);
		}
	};
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaManagedStateDimensionsTest, "Wuwa.Movement.ManagedState.LegalityAndDimensions",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaManagedStateDimensionsTest::RunTest(const FString& Parameters)
{
	using namespace WuwaUnifiedMovementStateTests;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	using P = EWuwaPositionState;
	using M = EWuwaMoveState;
	const TMap<P, TArray<M>> Legal = {
		{P::None, {M::Other}},
		{P::Ground, {M::Other, M::Stand, M::Walk, M::WalkStop, M::Run, M::RunStop, M::Sprint, M::SprintStop, M::Dodge}},
		{P::Air, {M::Other, M::Dodge, M::Jump, M::Fall, M::Glide, M::Flying}},
		{P::Climb, {M::Other, M::NormalClimb, M::FastClimb}},
		{P::Water, {M::Other, M::NormalSwim, M::FastSwim}}
	};
	for (const auto& Position : Legal)
	{
		for (uint8 Index = 0; Index <= static_cast<uint8>(M::Flying); ++Index)
		{
			const M Move = static_cast<M>(Index);
			TestEqual(FString::Printf(TEXT("Position %d / move %d legality"), static_cast<int32>(Position.Key), Index),
				F.State->IsMoveStateLegal(Position.Key, Move), Position.Value.Contains(Move));
		}
	}
	TestFalse(TEXT("Unknown position fails closed"), F.State->IsMoveStateLegal(static_cast<P>(255), M::Other));
	TestFalse(TEXT("Unknown movement fails closed"), F.State->IsMoveStateLegal(P::Ground, static_cast<M>(255)));
	TestFalse(TEXT("Ground state rejects airborne movement"), F.State->SetMoveState(M::Jump, EWuwaGait::Run));
	TestFalse(TEXT("Unknown gait fails closed"), F.State->SetMoveState(M::Stand, static_cast<EWuwaGait>(255)));
	TestFalse(TEXT("Unknown position is rejected"), F.State->SetPositionState(static_cast<P>(255)));
	const int32 InitialRevision = F.State->GetStateData().Revision;
	TestTrue(TEXT("The same valid state is an accepted no-op"), F.State->SetMoveState(M::Stand, EWuwaGait::Run));
	TestEqual(TEXT("Identical state does not publish another revision"), F.State->GetStateData().Revision, InitialRevision);

	// Each dimension has its own setter and event, as in the original CharacterUnifiedStateComponent.
	UWuwaStateEventRecorder* Recorder = NewObject<UWuwaStateEventRecorder>(F.Character);
	Recorder->Bind(F.State);
	TestTrue(TEXT("Direction changes through its own setter"), F.State->SetDirectionState(EWuwaDirectionState::LockDirection));
	TestFalse(TEXT("Setting the same direction reports no change"), F.State->SetDirectionState(EWuwaDirectionState::LockDirection));
	TestEqual(TEXT("Only the direction event is broadcast"), Recorder->Events, TArray<FString>{TEXT("Direction FaceDirection->LockDirection")});
	Recorder->Events.Reset();
	TestTrue(TEXT("An action state is written directly"), F.State->SetMoveState(M::Dodge, EWuwaGait::Run));
	TestEqual(TEXT("Writing a move state with the same gait broadcasts only the move event"), Recorder->Events,
		TArray<FString>{TEXT("Move Stand->Dodge")});
	TestTrue(TEXT("Dodge is reported to animation as an action state"), F.State->GetStateData().bHasActionOverride);
	TestTrue(TEXT("Position and direction are untouched by a move write"), F.State->GetStateData().PositionState == P::Ground
		&& F.State->GetStateData().DirectionState == EWuwaDirectionState::LockDirection);
	TestTrue(TEXT("There is no lease: an ordinary write replaces the action state"), F.State->SetMoveState(M::Stand, EWuwaGait::Walk));
	TestFalse(TEXT("The compatibility flag follows the move state"), F.State->GetStateData().bHasActionOverride);
	TestEqual(TEXT("A gait change has its own event after the move event"), Recorder->Events,
		(TArray<FString>{TEXT("Move Stand->Dodge"), TEXT("Move Dodge->Stand"), TEXT("Gait Run->Walk")}));

	// Position follows the physical movement mode through the CMC event, not RoleGait polling.
	Recorder->Events.Reset();
	F.Movement->SetMovementMode(MOVE_Falling);
	TestTrue(TEXT("Falling moves the state into Air"), F.State->GetStateData().PositionState == P::Air);
	TestTrue(TEXT("The falling handler writes Other, then RoleGait resolves Fall in the same frame"),
		F.State->GetStateData().MoveState == M::Fall);
	TestTrue(TEXT("Leaving the ground broadcasts the position change before the airborne move"),
		Recorder->IndexOf(TEXT("Position Ground->Air")) == 0 && Recorder->IndexOf(TEXT("Move Stand->Other")) > 0
		&& Recorder->IndexOf(TEXT("Move Other->Fall")) > Recorder->IndexOf(TEXT("Move Stand->Other")));
	Recorder->Events.Reset();
	F.Movement->SetMovementMode(MOVE_Walking);
	TestTrue(TEXT("Walking returns the state to Ground"), F.State->GetStateData().PositionState == P::Ground);
	TestTrue(TEXT("Original OnLand writes Other before the position event is broadcast"),
		Recorder->IndexOf(TEXT("Move Fall->Other")) >= 0
		&& Recorder->IndexOf(TEXT("Move Fall->Other")) < Recorder->IndexOf(TEXT("Position Air->Ground")));
	TestTrue(TEXT("RoleGait then settles the landed character to Stand"), F.State->GetStateData().MoveState == M::Stand);
	TestTrue(TEXT("Walk preference is unchanged by position changes"), F.Movement->GetDesiredGait() == EWuwaGait::Run);

	// Dash only writes Dodge at the start. RoleGait keeps the original rules afterwards.
	TestTrue(TEXT("Semantic movement is routed"), F.Move(FVector2D(0.f, 1.f), 1.0));
	TestEqual(TEXT("The routed axis reaches the character through its dynamic delegate"),
		F.Character->GetPlayerInputState().MoveAxis, FVector2D(0.f, 1.f));
	TestTrue(TEXT("The managed context sees the routed movement intent"), F.Gait->ReadMovementContext().bHasMoveInput);
	TestTrue(TEXT("Held movement resolves Run"), F.State->GetStateData().MoveState == M::Run);
	TestTrue(TEXT("A Dash-like action writes Dodge"), F.State->SetMoveState(M::Dodge, EWuwaGait::Run));
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Original RoleGait: a held direction overwrites Dodge on the next refresh"), F.State->GetStateData().MoveState == M::Run);

	F.Movement->Velocity = FVector(-310.f, 0.f, 0.f);
	F.Move(FVector2D::ZeroVector, 1.2);
	TestTrue(TEXT("Releasing a moving Run enters RunStop"), F.State->GetStateData().MoveState == M::RunStop);
	TestTrue(TEXT("A no-input Dash writes Dodge"), F.State->SetMoveState(M::Dodge, EWuwaGait::Run));
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Original RoleGait: without input Dodge is kept while the character still moves"),
		F.State->GetStateData().MoveState == M::Dodge);
	const FWuwaLocomotionAnimData DuringDash = F.Snapshot(*this);
	TestTrue(TEXT("Animation sees the action state"), DuringDash.bHasUnifiedState && DuringDash.bHasActionOverride);
	TestFalse(TEXT("Dash residual speed cannot trigger ordinary Stop animation"), DuringDash.bWantsToStop);
	TestFalse(TEXT("Dash is not ground locomotion"), DuringDash.bGroundMoveActive);
	TestEqual(TEXT("State decisions never zero physical velocity"), F.Movement->Velocity, FVector(-310.f, 0.f, 0.f));
	F.Movement->Velocity = FVector::ZeroVector;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Dodge settles to Stand once the character stops, without manufacturing RunStop"),
		F.State->GetStateData().MoveState == M::Stand);
	TestFalse(TEXT("Animation remains out of Stop after the action settles"), F.Snapshot(*this).bWantsToStop);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaManagedSprintPipelineTest, "Wuwa.Movement.ManagedState.RoutedSprintAndAnimation",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaManagedSprintPipelineTest::RunTest(const FString& Parameters)
{
	using namespace WuwaUnifiedMovementStateTests;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	using M = EWuwaMoveState;
	UWuwaMovementSettings* Settings = NewObject<UWuwaMovementSettings>(F.Character);
	Settings->Walk.MaxSpeed = 210.f;
	Settings->Walk.MaxAcceleration = 1200.f;
	Settings->Walk.GroundFriction = 6.f;
	Settings->Walk.BrakingDeceleration = 900.f;
	Settings->Sprint.MaxSpeed = 940.f;
	Settings->Sprint.MaxAcceleration = 2700.f;
	Settings->Sprint.GroundFriction = 4.f;
	Settings->Sprint.BrakingDeceleration = 1300.f;
	F.Movement->MovementSettings = Settings;
	TestTrue(TEXT("Movement command reaches the controlled character"), F.Move(FVector2D(0.f, 1.f), 1.0));
	TestTrue(TEXT("The movement command updates the character input snapshot"), F.Character->GetPlayerInputState().bHasMoveInput);
	TestTrue(TEXT("Walk/Run command reaches managed gait policy"), F.Dispatch(F.WalkRunBinding, EWuwaInputPhase::Pressed, 1.01));
	// 走跑键只改偏好；真实游戏里本帧 CMC Tick 开头 RoleGait 才按新偏好决定状态，测试不跑 Tick，手动刷新一次。
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Managed state accepts the Walk preference"), F.State->GetStateData().MoveState == M::Walk);
	F.Movement->Velocity = FVector(350.f, 0.f, 0.f);
	TestEqual(TEXT("Walk applies configured speed cap"), F.Movement->MaxWalkSpeed, 210.f);
	TestEqual(TEXT("Walk applies configured acceleration"), F.Movement->MaxAcceleration, 1200.f);
	TestEqual(TEXT("Walk applies configured friction"), F.Movement->GroundFriction, 6.f);
	TestEqual(TEXT("Walk applies configured braking"), F.Movement->BrakingDecelerationWalking, 900.f);

	UObject* Window = NewObject<UInputAction>(F.Character);
	F.World->TimeSeconds = 2.0;
	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	TestTrue(TEXT("Temporary sprint is accepted through the managed state"), F.State->GetStateData().MoveState == M::Sprint);
	TestTrue(TEXT("Sprint keeps the saved Walk preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	TestEqual(TEXT("Sprint applies its own configured speed cap"), F.Movement->MaxWalkSpeed, 940.f);
	TestEqual(TEXT("Sprint applies its own configured acceleration"), F.Movement->MaxAcceleration, 2700.f);
	TestEqual(TEXT("Sprint applies its own configured friction"), F.Movement->GroundFriction, 4.f);
	TestEqual(TEXT("Sprint applies its own configured braking"), F.Movement->BrakingDecelerationWalking, 1300.f);
	F.State->SetDirectionState(EWuwaDirectionState::LockDirection);
	const FWuwaLocomotionAnimData Sprint = F.Snapshot(*this);
	TestTrue(TEXT("Anim snapshot reads actual unified Sprint"), Sprint.bHasUnifiedState && Sprint.MoveState == M::Sprint);
	TestTrue(TEXT("Anim snapshot carries Ground and direction state"), Sprint.PositionState == EWuwaPositionState::Ground
		&& Sprint.DirectionState == EWuwaDirectionState::LockDirection);
	TestTrue(TEXT("Accepted Sprint enables ground movement animation"), Sprint.bGroundMoveActive && Sprint.bStateGroundSprint);
	TestTrue(TEXT("Anim view keeps Walk preference and Sprint result separate"), Sprint.DesiredGait == EWuwaGait::Walk
		&& Sprint.AllowedGait == EWuwaGait::Sprint && Sprint.StopGait == EWuwaGait::Sprint);
	TestEqual(TEXT("Changing policy leaves actual speed independent of the cap"), Sprint.GroundSpeed, 350.f);
	F.World->TimeSeconds = 2.99;
	F.Gait->RefreshPolicy();
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	TestTrue(TEXT("Temporary sprint survives until its one-second deadline"), F.State->GetStateData().MoveState == M::Sprint);
	F.World->TimeSeconds = 3.0;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Expiration runs without an animation update or notify Tick"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Expiration restores the retained Walk preference"), F.State->GetStateData().MoveState == M::Walk);
	TestEqual(TEXT("Walk configuration is reapplied at expiry"), F.Movement->MaxWalkSpeed, 210.f);
	TestEqual(TEXT("Expiry does not reset velocity"), F.Movement->Velocity, FVector(350.f, 0.f, 0.f));

	// The same semantic Dash action drives the hold snapshot even when no ASC accepts a GA.
	TestNull(TEXT("This input path does not require a working ASC"), F.Controller->GetASC());
	F.Dispatch(F.SprintBinding, EWuwaInputPhase::Pressed, 4.0);
	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	F.Sample(Window, 4.2);
	TestTrue(TEXT("Exactly the threshold remains temporary"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::Temporary);
	F.Sample(Window, 4.21);
	TestTrue(TEXT("Routed semantic hold becomes sustained"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::Sustained);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	F.Dispatch(F.SprintBinding, EWuwaInputPhase::Released, 4.3);
	F.Sample(Window, 4.4);
	TestTrue(TEXT("Release after window End cannot demote committed sustained sprint"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::Sustained);
	F.Move(FVector2D::ZeroVector, 4.5);
	TestTrue(TEXT("Releasing movement clears sustained request despite residual velocity"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Actual Sprint transitions to SprintStop"), F.State->GetStateData().MoveState == M::SprintStop);
	const FWuwaLocomotionAnimData Stop = F.Snapshot(*this);
	TestTrue(TEXT("Animation selects the last actual Sprint stop"), Stop.bWantsToStop && Stop.StopGait == EWuwaGait::Sprint);
	TestFalse(TEXT("Stop is not active ground locomotion"), Stop.bGroundMoveActive);
	F.Movement->Velocity = FVector::ZeroVector;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Completed stop settles to Stand"), F.State->GetStateData().MoveState == M::Stand);
	TestTrue(TEXT("Zero speed does not change the stop clip's saved gait"), F.Snapshot(*this).StopGait == EWuwaGait::Sprint);
	F.Move(FVector2D(0.f, 1.f), 5.0);
	TestTrue(TEXT("The next movement uses Walk rather than reviving Sprint"), F.State->GetStateData().MoveState == M::Walk);
	TestTrue(TEXT("The next actual gait updates StopGait"), WuwaTestGait::Of(F.Movement)->StopGait == EWuwaGait::Walk);
	F.Sample(Window, 5.3);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	TestTrue(TEXT("Late window callbacks cannot revive a consumed request"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaManagedGaitRestrictionTest, "Wuwa.Movement.ManagedState.RestrictionsAndPosition",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaManagedGaitRestrictionTest::RunTest(const FString& Parameters)
{
	using namespace WuwaUnifiedMovementStateTests;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	using M = EWuwaMoveState;
	using P = EWuwaPositionState;
	TestTrue(TEXT("Restriction fixture receives the routed movement command"), F.Move(FVector2D(0.f, 1.f), 1.0));
	TestTrue(TEXT("Restriction policy starts with real movement input"), F.Gait->ReadMovementContext().bHasMoveInput);
	WuwaTestGait::SetDesiredGait(F.Movement, EWuwaGait::Walk);
	TestTrue(TEXT("The Walk preference is stored by the movement state component"), F.State->IsWalkPreferred());
	UObject* ReasonA = NewObject<UInputAction>(F.Character);
	UObject* ReasonB = NewObject<UInputAction>(F.Character);
	UObject* Window = NewObject<UInputAction>(F.Character);
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, true);
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, true);
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Sprint, true);
	WuwaTestGait::SetDesiredGait(F.Movement, EWuwaGait::Sprint);
	TestTrue(TEXT("A legacy Sprint request preserves Walk preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	TestTrue(TEXT("Blocked Sprint falls back to the preferred Walk"), F.State->GetStateData().MoveState == M::Walk);
	TestTrue(TEXT("Blocking execution does not erase the sprint request"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::Sustained);
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, false);
	WuwaTestGait::SetSprintAllowed(F.Movement, true);
	TestFalse(TEXT("Removing one source, or the CMC compatibility source, cannot release another source"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Sprint, false);
	TestTrue(TEXT("Each blocking source releases only its own contribution"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	TestTrue(TEXT("Once every source releases, the pending request can resolve to Sprint"), F.State->GetStateData().MoveState == M::Sprint);
	WuwaTestGait::Of(F.Movement)->ResetSprintRequest();
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Walk, true);
	TestTrue(TEXT("A blocked preference falls back to allowed Run"), F.State->GetStateData().MoveState == M::Run);
	TestTrue(TEXT("Fallback does not overwrite preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Run, true);
	TestTrue(TEXT("Disallowing both ground gaits resolves to Other"), F.State->GetStateData().MoveState == M::Other);
	const FWuwaLocomotionAnimData Blocked = F.Snapshot(*this);
	TestFalse(TEXT("Movement input cannot bypass restrictions in animation"), Blocked.bGroundMoveActive || Blocked.bIsGoingToMove);
	F.Gait->ResetSprintRequest();
	TestFalse(TEXT("Clearing sprint leaves other gait restrictions intact"), F.Gait->IsGaitAllowed(EWuwaGait::Walk));
	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Walk, false);
	F.Gait->SetGaitBlocked(ReasonB, EWuwaGait::Run, false);
	UObject* DeadReason = NewObject<UInputAction>(F.Character);
	F.Gait->SetGaitBlocked(DeadReason, EWuwaGait::Sprint, true);
	DeadReason->MarkAsGarbage();
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("A destroyed restriction source cannot leave the gait permanently blocked"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));

	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	TestTrue(TEXT("A Dash-like action writes Dodge on the ground"), F.State->SetMoveState(M::Dodge, EWuwaGait::Walk));
	F.Movement->Velocity = FVector(170.f, 0.f, 210.f);
	F.Movement->SetMovementMode(MOVE_Falling);
	TestTrue(TEXT("Ground to Air follows the physical movement mode event"), F.State->GetStateData().PositionState == P::Air);
	TestTrue(TEXT("Leaving Ground clears active and retained sprint requests"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Original falling handler replaces Dodge; positive vertical velocity then resolves to Jump"),
		F.State->GetStateData().MoveState == M::Jump);
	F.Movement->Velocity.Z = -10.f;
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Negative vertical velocity resolves to Fall"), F.State->GetStateData().MoveState == M::Fall);
	TestTrue(TEXT("Dodge is legal in Air"), F.State->SetMoveState(M::Dodge, EWuwaGait::Walk));
	F.Gait->RefreshPolicy();
	TestTrue(TEXT("Jump/Fall resolution does not overwrite an airborne action state"), F.State->GetStateData().MoveState == M::Dodge);
	F.Movement->SetMovementMode(MOVE_Flying);
	TestTrue(TEXT("Physical flying resolves to Flying"), F.State->GetStateData().PositionState == P::Air
		&& F.State->GetStateData().MoveState == M::Flying);
	F.Movement->SetMovementMode(MOVE_Swimming);
	TestTrue(TEXT("Swimming with movement input resolves to Water / NormalSwim"), F.State->GetStateData().PositionState == P::Water
		&& F.State->GetStateData().MoveState == M::NormalSwim);
	F.Move(FVector2D::ZeroVector, 1.1);
	TestTrue(TEXT("Original RoleGait: releasing movement in water resolves to Other"), F.State->GetStateData().MoveState == M::Other);
	F.Move(FVector2D(0.f, 1.f), 1.2);
	TestTrue(TEXT("Pressing again in water resolves to NormalSwim"), F.State->GetStateData().MoveState == M::NormalSwim);
	F.Movement->SetMovementMode(MOVE_Custom, static_cast<uint8>(ECustomMoveMode::MOVE_Climb));
	TestTrue(TEXT("Climbing with movement input resolves to Climb / NormalClimb"), F.State->GetStateData().PositionState == P::Climb
		&& F.State->GetStateData().MoveState == M::NormalClimb);
	F.Move(FVector2D::ZeroVector, 1.3);
	TestTrue(TEXT("Original RoleGait: releasing movement while climbing resolves to Other"), F.State->GetStateData().MoveState == M::Other);
	F.Move(FVector2D(0.f, 1.f), 1.4);
	TestEqual(TEXT("Policy changes never reset horizontal speed"), F.Movement->Velocity.X, 170.0);
	F.Movement->SetMovementMode(MOVE_None);
	TestTrue(TEXT("No physical movement mode resolves to None / Other"), F.State->GetStateData().PositionState == P::None
		&& F.State->GetStateData().MoveState == M::Other);
	F.Movement->SetMovementMode(MOVE_Walking);
	WuwaTestGait::Of(F.Movement)->SampleSprintWindow(Window, 5.f, 0.2f);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	TestTrue(TEXT("Returning to Ground retains Walk but not the departed sprint window"), F.State->GetStateData().MoveState == M::Walk
		&& WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);

	F.Gait->SetGaitBlocked(ReasonA, EWuwaGait::Sprint, true);
	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	F.Gait->ResetSprintRequest();
	TestTrue(TEXT("Sprint-only reset clears the request"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);
	TestFalse(TEXT("Sprint-only reset preserves the restriction sources"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	WuwaTestGait::Of(F.Movement)->OpenSprintWindow(Window);
	F.Gait->ResetRuntime();
	TestTrue(TEXT("Runtime reset clears all restriction sources"), F.Gait->IsGaitAllowed(EWuwaGait::Sprint));
	WuwaTestGait::Of(F.Movement)->SampleSprintWindow(Window, 5.f, 0.2f);
	WuwaTestGait::Of(F.Movement)->CloseSprintWindow(Window);
	TestTrue(TEXT("Runtime reset clears unfinished and retained sprint without late resurrection"), WuwaTestGait::Of(F.Movement)->ReadSprintDesire() == EWuwaSprintDesire::None);
	TestTrue(TEXT("Runtime reset retains the player's Walk preference"), F.Movement->GetDesiredGait() == EWuwaGait::Walk);
	return true;
}

#endif
