#if WITH_DEV_AUTOMATION_TESTS

#include "Misc/AutomationTest.h"
#include "Engine/World.h"
#include "UObject/Script.h"
#include "Game/NewWorld/Character/Role/WuwaCharacter.h"
#include "Game/NewWorld/Character/Common/Component/Abilities/WuwaUnifiedStateBridgeComponent.h"
#include "Game/NewWorld/Character/Common/Component/Combat/WuwaFightStateBridgeComponent.h"

namespace WuwaFightStateTests
{
	using S = EWuwaFightState;

	// Exercise the actual generated C# class through ProcessEvent, without a native policy substitute.
	struct FFixture
	{
		UWorld* World = UWorld::CreateWorld(EWorldType::Game, false);
		AWuwaCharacter* Character = nullptr;
		UWuwaFightStateBridgeComponent* State = nullptr;

		FFixture()
		{
			Character = SpawnCharacter();
			if (Character && Character->EnsureFightStateSystem()) State = Character->FightStateComponent;
		}

		~FFixture()
		{
			if (World) World->DestroyWorld(false);
		}

		AWuwaCharacter* SpawnCharacter() const
		{
			if (!World) return nullptr;
			FActorSpawnParameters Spawn;
			Spawn.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
			Spawn.ObjectFlags |= RF_Transient;
			return World->SpawnActor<AWuwaCharacter>(Spawn);
		}

		bool IsReady(FAutomationTestBase& Test) const
		{
			if (!Test.TestNotNull(TEXT("Character exists"), Character)
				|| !Test.TestNotNull(TEXT("Managed fight state is assembled"), State)) return false;
			bool bReady = Test.TestEqual(TEXT("Fight state uses the configured managed class"),
				State->GetClass(), Character->FightStateClass.LoadSynchronous());
			bReady &= Test.TestEqual(TEXT("Fight state is generated by UnrealSharp"),
				State->GetClass()->GetClass()->GetFName(), FName(TEXT("CSClass")));
			bReady &= Test.TestTrue(TEXT("Managed policy responds through the native reflection bridge"),
				State->CheckSwitchState(S::Skill, 0));
			return bReady;
		}
	};

	void TestSnapshot(FAutomationTestBase& Test, const FString& Context,
		const FWuwaFightStateData& Actual, const FWuwaFightStateData& Expected)
	{
		Test.TestEqual(Context + TEXT(" state"), static_cast<uint8>(Actual.State), static_cast<uint8>(Expected.State));
		Test.TestEqual(Context + TEXT(" priority"), Actual.SubStatePriority, Expected.SubStatePriority);
		Test.TestEqual(Context + TEXT(" handle"), Actual.Handle, Expected.Handle);
	}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaFightStateAssemblyTest, "Wuwa.Combat.FightState.ManagedAssemblyAndIsolation",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaFightStateAssemblyTest::RunTest(const FString& Parameters)
{
	using namespace WuwaFightStateTests;
	FEditorScriptExecutionGuard ScriptExecutionGuard;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	TestSnapshot(*this, TEXT("New component is empty"), F.State->GetStateData(), FWuwaFightStateData{});

	if (!TestTrue(TEXT("Existing movement state can be assembled alongside fight state"),
		F.Character->EnsureMovementStateSystem())
		|| !TestNotNull(TEXT("Unified state exists"), F.Character->UnifiedStateComponent.Get())) return false;
	const FWuwaUnifiedStateData BeforeMovement = F.Character->UnifiedStateComponent->GetStateData();
	const int32 Handle = F.State->TrySwitchState(S::Skill, 42);
	TestTrue(TEXT("Skill acquires a fight handle"), Handle > 0);
	const FWuwaFightStateData BeforeEnsure = F.State->GetStateData();
	TestTrue(TEXT("Repeated assembly succeeds"), F.Character->EnsureFightStateSystem());
	TestEqual(TEXT("Repeated assembly reuses the same component"), F.Character->FightStateComponent.Get(), F.State);
	TestSnapshot(*this, TEXT("Repeated assembly preserves an active state"), F.State->GetStateData(), BeforeEnsure);

	AWuwaCharacter* Other = F.SpawnCharacter();
	if (!TestNotNull(TEXT("Second character exists"), Other)
		|| !TestTrue(TEXT("Second character assembles its fight state"), Other->EnsureFightStateSystem())
		|| !TestNotNull(TEXT("Second fight state exists"), Other->FightStateComponent.Get())) return false;
	TestTrue(TEXT("Characters own different fight components"), Other->FightStateComponent.Get() != F.State);
	TestSnapshot(*this, TEXT("Second character starts empty"), Other->FightStateComponent->GetStateData(), FWuwaFightStateData{});
	TestTrue(TEXT("Second character can enter hit independently"), Other->FightStateComponent->TrySwitchState(S::Hit, 0) > 0);
	Other->FightStateComponent->ResetState();
	TestSnapshot(*this, TEXT("Other character cannot replace or reset this skill"), F.State->GetStateData(), BeforeEnsure);

	TestTrue(TEXT("Fight state can change from skill to hit"), F.State->TrySwitchState(S::Hit, 0) > 0);
	F.State->ResetState();
	const FWuwaUnifiedStateData AfterMovement = F.Character->UnifiedStateComponent->GetStateData();
	TestTrue(TEXT("Fight transitions leave position unchanged"), AfterMovement.PositionState == BeforeMovement.PositionState);
	TestTrue(TEXT("Fight transitions leave movement unchanged"), AfterMovement.MoveState == BeforeMovement.MoveState);
	TestTrue(TEXT("Fight transitions leave direction unchanged"), AfterMovement.DirectionState == BeforeMovement.DirectionState);
	TestTrue(TEXT("Fight transitions leave gait unchanged"), AfterMovement.Gait == BeforeMovement.Gait);
	TestEqual(TEXT("Fight transitions do not write an action move state"), AfterMovement.bHasActionOverride, BeforeMovement.bHasActionOverride);
	TestEqual(TEXT("Fight transitions do not publish movement revisions"), AfterMovement.Revision, BeforeMovement.Revision);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaFightStatePriorityTest, "Wuwa.Combat.FightState.PriorityAndPureQueries",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaFightStatePriorityTest::RunTest(const FString& Parameters)
{
	using namespace WuwaFightStateTests;
	FEditorScriptExecutionGuard ScriptExecutionGuard;
	FFixture F;
	if (!F.IsReady(*this)) return false;

	struct FCategoryCase { S State; bool bEqualPriorityAllowed; };
	const FCategoryCase Categories[] = {
		{S::Skill, true}, {S::Hit, true}, {S::SkillOverrideHit, false}, {S::ParryHit, false},
		{S::SkillOverrideParry, false}, {S::WeaknessBreak, true}, {S::SkillOverrideWeaknessBreak, false},
		{S::Captured, false}, {S::SpecialSkill, true}, {S::StateMachine, false}
	};
	for (const FCategoryCase& Category : Categories)
	{
		F.State->ResetState();
		const int32 InitialHandle = F.State->TrySwitchState(Category.State, 127);
		TestTrue(TEXT("Each declared category is a valid initial state"), InitialHandle > 0);
		const FWuwaFightStateData Initial = F.State->GetStateData();
		for (const FCategoryCase& Target : Categories)
		{
			const FString Label = FString::Printf(TEXT("Category %d -> %d"),
				static_cast<int32>(Category.State), static_cast<int32>(Target.State));
			const bool bExpected = Target.State == Category.State ? Category.bEqualPriorityAllowed
				: static_cast<uint8>(Target.State) > static_cast<uint8>(Category.State);
			TestEqual(Label, F.State->CheckSwitchState(Target.State, 127), bExpected);
		}
		TestTrue(TEXT("A higher subpriority is allowed within a category"), F.State->CheckSwitchState(Category.State, 255));
		TestFalse(TEXT("A lower subpriority is rejected within a category"), F.State->CheckSwitchState(Category.State, 0));
		TestSnapshot(*this, TEXT("All eligibility queries are pure"), F.State->GetStateData(), Initial);
		TestEqual(TEXT("Rejected subpriority cannot replace the state"), F.State->TrySwitchState(Category.State, 0), 0);
		TestSnapshot(*this, TEXT("Rejected transition preserves its owner"), F.State->GetStateData(), Initial);
		const int32 EqualHandle = F.State->TrySwitchState(Category.State, 127);
		TestEqual(TEXT("Equal-priority commit follows the same category rule"), EqualHandle > 0, Category.bEqualPriorityAllowed);
		TestEqual(TEXT("Only a successful commit consumes the next handle"),
			F.State->TrySwitchState(Category.State, 255), InitialHandle + (Category.bEqualPriorityAllowed ? 2 : 1));
	}

	F.State->ResetState();
	const int32 SkillHandle = F.State->TrySwitchState(S::Skill, 255);
	TestTrue(TEXT("Higher category wins even with the lowest subpriority"), F.State->CheckSwitchState(S::Hit, 0));
	TestEqual(TEXT("Cross-category transition commits"), F.State->TrySwitchState(S::Hit, 0), SkillHandle + 1);
	TestFalse(TEXT("Highest subpriority cannot overcome a lower category"), F.State->CheckSwitchState(S::Skill, 255));
	TestEqual(TEXT("Lower category cannot commit"), F.State->TrySwitchState(S::Skill, 255), 0);
	const FWuwaFightStateData BeforeInvalid = F.State->GetStateData();
	struct FInvalidCase { S State; int32 Priority; };
	const FInvalidCase InvalidCases[] = {
		{S::None, 0}, {static_cast<S>(11), 0}, {static_cast<S>(255), 0},
		{S::StateMachine, -1}, {S::StateMachine, 256}
	};
	for (const FInvalidCase& Invalid : InvalidCases)
	{
		TestFalse(TEXT("Invalid state or priority fails preflight"), F.State->CheckSwitchState(Invalid.State, Invalid.Priority));
		TestEqual(TEXT("Invalid state or priority cannot commit"), F.State->TrySwitchState(Invalid.State, Invalid.Priority), 0);
	}
	TestSnapshot(*this, TEXT("Invalid requests leave active state intact"), F.State->GetStateData(), BeforeInvalid);
	TestEqual(TEXT("Failed requests consume no handles"), F.State->TrySwitchState(S::SpecialSkill, 255), BeforeInvalid.Handle + 1);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FWuwaFightStateHandleTest, "Wuwa.Combat.FightState.StaleHandlesAndReset",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FWuwaFightStateHandleTest::RunTest(const FString& Parameters)
{
	using namespace WuwaFightStateTests;
	FEditorScriptExecutionGuard ScriptExecutionGuard;
	FFixture F;
	if (!F.IsReady(*this)) return false;
	TestFalse(TEXT("Zero cannot release an empty slot"), F.State->ExitState(0));
	const int32 OldSkill = F.State->TrySwitchState(S::Skill, 0);
	const int32 Hit = F.State->TrySwitchState(S::Hit, 0);
	TestTrue(TEXT("Hit has a newer handle than the interrupted skill"), OldSkill > 0 && Hit > OldSkill);
	const FWuwaFightStateData HitState = F.State->GetStateData();
	TestFalse(TEXT("Late skill cleanup cannot release the replacing hit"), F.State->ExitState(OldSkill));
	TestFalse(TEXT("Zero is never an active handle"), F.State->ExitState(0));
	TestFalse(TEXT("Negative handle is invalid"), F.State->ExitState(-1));
	TestSnapshot(*this, TEXT("Rejected cleanup preserves the hit"), F.State->GetStateData(), HitState);
	TestTrue(TEXT("The current owner can exit"), F.State->ExitState(Hit));
	TestSnapshot(*this, TEXT("Exit clears all published state fields"), F.State->GetStateData(), FWuwaFightStateData{});
	TestFalse(TEXT("Repeated exit cannot release anything"), F.State->ExitState(Hit));

	const int32 BeforeReset = F.State->TrySwitchState(S::Skill, 0);
	TestEqual(TEXT("Exit and failed cleanup consume no handles"), BeforeReset, Hit + 1);
	F.State->ResetState();
	F.State->ResetState();
	TestSnapshot(*this, TEXT("Reset leaves an empty slot"), F.State->GetStateData(), FWuwaFightStateData{});
	const int32 AfterReset = F.State->TrySwitchState(S::Skill, 0);
	TestEqual(TEXT("Reset preserves the monotonic handle counter"), AfterReset, BeforeReset + 1);
	TestFalse(TEXT("Pre-reset cleanup cannot release a post-reset action"), F.State->ExitState(BeforeReset));
	const int32 Replacement = F.State->TrySwitchState(S::Skill, 0);
	TestEqual(TEXT("Equal-priority replacement still receives a distinct handle"), Replacement, AfterReset + 1);
	TestFalse(TEXT("The replaced equal-priority owner cannot release the new run"), F.State->ExitState(AfterReset));
	TestEqual(TEXT("The replacement still owns the slot"), F.State->GetStateData().Handle, Replacement);
	TestTrue(TEXT("Latest owner can finish"), F.State->ExitState(Replacement));
	return true;
}

#endif
